{% set version = "3.6.1" %}

package:
  name: lapack
  version: {{ version }}

source:
  fn: lapack-{{ version }}.tgz
  url: http://www.netlib.org/lapack/lapack-{{ version }}.tgz
  sha1: 7220a9bc9c766cb513007f313b804d88f110c228

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - gcc  # [unix]
    - cloog 0.18.0 10  # [unix]
  run:
    - libgcc  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/liblapack.so  # [linux]
    - test -f ${PREFIX}/lib/liblapack.dylib  # [osx]

about:
  home: http://www.netlib.org/lapack
  license: BSD 3-Clause
  summary: Linear Algebra PACKage

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
