# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "awSlPO0EOA5vcQ7dYhHCHIZpdqx0Hpd1A0/FEdGc5/Q/mm3IGSO5D3sZLWBcvZPc8yoBvtVsQUTfaTB7eoYq6BiO5yPDxXqJgMxnMaAk7aJ7Z773sSPIEi0+4fBJ7PkXmlZyWD6ZS/dnhQebqR2geQrW801jMC2I/w83KjbTXvYqniFQ2vHivpf4HLkJnXnuMlSsTrrfScFDManJFLFv7fl6AZTEZy4yqIAwAjP4MGSAoIkgc8oztoF5D97rR3D608+w160n0JiO0J/5PiW6pDOX1tp66teN09Yff2OBZYzJd+qboki2wIyVo2rcXaZ0VRE2tezJvfuT3NnSrGVg3edHg0t4AYX1Qfg9jf478hARVw9xbM38GUjGDeZzDPQf/ykEpQ9AZqkjSm08+RvBX3stY7CBVumUYeskbjkz/biiULRMD1ZKmKdvIhMb0cb6W+/2ZnBrTfC31rKsa5fQozsJTetQChTTjzZEZ73NoAQg44iLO6UPfIYrR3+YvR48pOxHeK3mP3Hnep6N4G8okfznRR+GSDvJnuH9PelQQ8HMkSy5PinYchuQzknqJtr4hJxOdyWnChuki+0x0G5Rh642KCAoLXYVwrunyK8P10GmzV/lC0Tkaa0vr+C+36pruOYQWKDGyjLf9z9LAprFp8vwHvb+fUsZaWObpm1886A="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
